"""initial_schema

Revision ID: 75c3a458603e
Revises: 
Create Date: 2026-07-12 11:52:55.207756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c3a458603e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialization')),
    sa.UniqueConstraint('name', name=op.f('uq_specialization_name'))
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('doctor',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('specialization_id', sa.Uuid(), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], name=op.f('fk_doctor_specialization_id_specialization')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_doctor_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor')),
    sa.UniqueConstraint('user_id', name=op.f('uq_doctor_user_id'))
    )
    op.create_index(op.f('ix_doctor_specialization_id'), 'doctor', ['specialization_id'], unique=False)
    op.create_table('patient',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_patient_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_user_id'))
    )
    op.create_table('appointment_slot',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('held_by', sa.Uuid(), nullable=True),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_appointment_slot_doctor_id_doctor'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['held_by'], ['user.id'], name=op.f('fk_appointment_slot_held_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_slot')),
    sa.UniqueConstraint('doctor_id', 'slot_date', 'start_time', name='uq_doctor_slot')
    )
    op.create_index('idx_slot_doctor_date', 'appointment_slot', ['doctor_id', 'slot_date'], unique=False)
    op.create_index('idx_slot_held_until', 'appointment_slot', ['held_until'], unique=False, postgresql_where=sa.text("status = 'held'"))
    op.create_index(op.f('ix_appointment_slot_status'), 'appointment_slot', ['status'], unique=False)
    op.create_table('doctor_leave',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_doctor_leave_doctor_id_doctor'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_leave')),
    sa.UniqueConstraint('doctor_id', 'leave_date', name='uq_doctor_leave')
    )
    op.create_index('idx_leave_doctor_date', 'doctor_leave', ['doctor_id', 'leave_date'], unique=False)
    op.create_table('doctor_schedule',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name=op.f('chk_doctor_schedule_chk_schedule_day')),
    sa.CheckConstraint('start_time < end_time', name=op.f('chk_doctor_schedule_chk_schedule_time')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_doctor_schedule_doctor_id_doctor'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_schedule')),
    sa.UniqueConstraint('doctor_id', 'day_of_week', name='uq_doctor_day')
    )
    op.create_index(op.f('ix_doctor_schedule_doctor_id'), 'doctor_schedule', ['doctor_id'], unique=False)
    op.create_table('appointment',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('symptom_severity', sa.String(length=10), nullable=True),
    sa.Column('ai_pre_visit_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_pre_visit_status', sa.String(length=20), nullable=False),
    sa.Column('ai_post_visit_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_post_visit_status', sa.String(length=20), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True),
    sa.Column('booking_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_appointment_doctor_id_doctor')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_appointment_patient_id_patient')),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slot.id'], name=op.f('fk_appointment_slot_id_appointment_slot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment'))
    )
    op.create_index('idx_appointment_doctor_date', 'appointment', ['doctor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_slot_id'), 'appointment', ['slot_id'], unique=False)
    op.create_index(op.f('ix_appointment_status'), 'appointment', ['status'], unique=False)
    op.create_table('calendar_event',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('patient_event_id', sa.String(length=255), nullable=True),
    sa.Column('doctor_event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('fk_calendar_event_appointment_id_appointment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_event')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_calendar_event_appointment_id'))
    )
    op.create_table('consultation',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('fk_consultation_appointment_id_appointment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_consultation_doctor_id_doctor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_consultation_appointment_id'))
    )
    op.create_table('notification',
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('fk_notification_appointment_id_appointment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_appointment_id'), 'notification', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_notification_status'), 'notification', ['status'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('prescription',
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultation.id'], name=op.f('fk_prescription_consultation_id_consultation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription')),
    sa.UniqueConstraint('consultation_id', name=op.f('uq_prescription_consultation_id'))
    )
    op.create_table('medication',
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], name=op.f('fk_medication_prescription_id_prescription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication'))
    )
    op.create_index('idx_medication_dates', 'medication', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_medication_prescription_id'), 'medication', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_prescription_id'), table_name='medication')
    op.drop_index('idx_medication_dates', table_name='medication')
    op.drop_table('medication')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_status'), table_name='notification')
    op.drop_index(op.f('ix_notification_appointment_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('consultation')
    op.drop_table('calendar_event')
    op.drop_index(op.f('ix_appointment_status'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_slot_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index('idx_appointment_doctor_date', table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_doctor_schedule_doctor_id'), table_name='doctor_schedule')
    op.drop_table('doctor_schedule')
    op.drop_index('idx_leave_doctor_date', table_name='doctor_leave')
    op.drop_table('doctor_leave')
    op.drop_index(op.f('ix_appointment_slot_status'), table_name='appointment_slot')
    op.drop_index('idx_slot_held_until', table_name='appointment_slot', postgresql_where=sa.text("status = 'held'"))
    op.drop_index('idx_slot_doctor_date', table_name='appointment_slot')
    op.drop_table('appointment_slot')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_specialization_id'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('specialization')
    # ### end Alembic commands ###
