"""add google oauth tokens

Revision ID: 8caeec00801b
Revises: 75c3a458603e
Create Date: 2026-07-13 19:32:12.626869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caeec00801b'
down_revision: Union[str, Sequence[str], None] = '75c3a458603e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_access_token', sa.String(length=2048), nullable=True))
    op.add_column('user', sa.Column('google_refresh_token', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_refresh_token')
    op.drop_column('user', 'google_access_token')
    # ### end Alembic commands ###
